"""Static seed data for Shadow Nexus."""

CYBER_CLASSES = [
    {
        "id": "security_analyst",
        "name": "Security Analyst",
        "icon": "shield-checkmark",
        "color": "#00F0FF",
        "description": "Master of threat detection and incident response. Analyzes anomalies before they become catastrophes.",
        "starting_stats": {"intelligence": 8, "hacking": 5, "networking": 7, "cryptography": 6, "programming": 5, "social_engineering": 4},
        "bonus": "+20% XP from forensics missions",
    },
    {
        "id": "penetration_tester",
        "name": "Penetration Tester",
        "icon": "bug",
        "color": "#FF003C",
        "description": "Elite offensive operative who breaks systems to make them stronger. Lives in the gray zone.",
        "starting_stats": {"intelligence": 6, "hacking": 9, "networking": 6, "cryptography": 5, "programming": 7, "social_engineering": 5},
        "bonus": "+25% damage with Exploit attacks",
    },
    {
        "id": "malware_hunter",
        "name": "Malware Hunter",
        "icon": "skull",
        "color": "#9D00FF",
        "description": "Reverses the darkest code. Tracks ghosts in the machine across the dark web.",
        "starting_stats": {"intelligence": 7, "hacking": 7, "networking": 5, "cryptography": 6, "programming": 8, "social_engineering": 4},
        "bonus": "Detect 1 enemy weakness per combat",
    },
    {
        "id": "network_defender",
        "name": "Network Defender",
        "icon": "wifi",
        "color": "#00FF41",
        "description": "Builds the walls that hold civilization together. Master of firewalls and intrusion prevention.",
        "starting_stats": {"intelligence": 6, "hacking": 4, "networking": 9, "cryptography": 5, "programming": 5, "social_engineering": 6},
        "bonus": "+30% Firewall ability effectiveness",
    },
    {
        "id": "digital_forensics",
        "name": "Digital Forensics Expert",
        "icon": "search",
        "color": "#FFB000",
        "description": "Reads the bones of dead systems. Recovers what was meant to stay buried.",
        "starting_stats": {"intelligence": 9, "hacking": 5, "networking": 6, "cryptography": 7, "programming": 5, "social_engineering": 5},
        "bonus": "+50% chance for rare loot drops",
    },
]

AVATARS = [
    {"id": f"avatar_{i+1}", "icon": ic, "color": col}
    for i, (ic, col) in enumerate([
        ("hardware-chip", "#00F0FF"), ("eye", "#9D00FF"), ("flash", "#00FF41"),
        ("skull", "#FF003C"), ("shield", "#FFB000"), ("planet", "#00F0FF"),
        ("rocket", "#9D00FF"), ("flame", "#FF003C"), ("snow", "#00F0FF"),
        ("glasses", "#00FF41"), ("pulse", "#9D00FF"), ("bug", "#FF003C"),
        ("wifi", "#00FF41"), ("nuclear", "#FFB000"), ("triangle", "#00F0FF"),
        ("diamond", "#9D00FF"), ("flower", "#FF003C"), ("ellipsis-horizontal", "#00FF41"),
        ("infinite", "#FFB000"), ("key", "#00F0FF"), ("scan", "#9D00FF"),
        ("rose", "#FF003C"),
    ])
]

CHAPTERS = [
    {"id": "ch1", "number": 1, "title": "The Awakening", "subtitle": "Mysterious cyber attacks ripple through Nexus City",
     "description": "Strange anomalies are surfacing across critical infrastructure. As a fresh recruit, you must trace the first whispers of a coming storm.",
     "location": "nexus-city", "required_level": 1, "boss": "Glitch Wraith"},
    {"id": "ch2", "number": 2, "title": "The Dark Network", "subtitle": "Investigate underground hacker collectives",
     "description": "Beneath Nexus City lies the Dark Web Market. Infiltrate the underground and find who pulls the strings.",
     "location": "dark-web-market", "required_level": 5, "boss": "Crypto Reaper"},
    {"id": "ch3", "number": 3, "title": "The Phantom Grid", "subtitle": "A rogue AI organization revealed",
     "description": "The signals all converge. The Phantom Grid is real, and it's already inside your network.",
     "location": "quantum-labs", "required_level": 10, "boss": "Phantom Sentinel"},
    {"id": "ch4", "number": 4, "title": "Digital War", "subtitle": "Large-scale cyber conflict across the grid",
     "description": "Open war on the wire. Cities go dark. You become a legend or a casualty.",
     "location": "cyber-academy", "required_level": 15, "boss": "War Daemon"},
    {"id": "ch5", "number": 5, "title": "Final Firewall", "subtitle": "Face the AI mastermind",
     "description": "Inside the Phantom Fortress, the Shadow King awaits. Only one mind walks out.",
     "location": "phantom-fortress", "required_level": 20, "boss": "Shadow King"},
]

MISSIONS = [
    # Chapter 1
    {"id": "m1", "chapter_id": "ch1", "order": 1, "title": "First Contact", "category": "network_security",
     "difficulty": "Easy", "story": "A bank's firewall logs show impossible traffic. Investigate Port 22 anomalies.",
     "objective": "Scan and identify the rogue open port", "learning": "Port scanning fundamentals (Nmap)",
     "rewards": {"xp": 100, "coins": 50, "items": ["nmap_basic"]}, "combat": False, "puzzle": "port_scan"},
    {"id": "m2", "chapter_id": "ch1", "order": 2, "title": "SQL of Shadows", "category": "web_security",
     "difficulty": "Easy", "story": "A municipal site leaks records. Demonstrate the SQL injection flaw.",
     "objective": "Identify the vulnerable login bypass", "learning": "SQL Injection — ' OR 1=1 --",
     "rewards": {"xp": 120, "coins": 60}, "combat": False, "puzzle": "sql_injection"},
    {"id": "m3", "chapter_id": "ch1", "order": 3, "title": "Caesar's Echo", "category": "cryptography",
     "difficulty": "Easy", "story": "Decrypt a ROT-style cipher intercepted from the attackers.",
     "objective": "Decode the message", "learning": "Caesar cipher / substitution",
     "rewards": {"xp": 140, "coins": 70, "items": ["energy_pack"]}, "combat": False, "puzzle": "caesar"},
    {"id": "m4", "chapter_id": "ch1", "order": 4, "title": "The Phisher", "category": "social_engineering",
     "difficulty": "Medium", "story": "Spot the phishing email before HQ falls.",
     "objective": "Identify red flags in suspicious comms", "learning": "Social engineering indicators",
     "rewards": {"xp": 180, "coins": 90}, "combat": False, "puzzle": "phishing"},
    {"id": "m5", "chapter_id": "ch1", "order": 5, "title": "Glitch Wraith", "category": "boss",
     "difficulty": "Hard", "story": "Confront the entity behind the attacks. Chapter 1 BOSS.",
     "objective": "Defeat Glitch Wraith in cyber combat", "learning": "Combined operations",
     "rewards": {"xp": 500, "coins": 300, "items": ["quantum_helmet"]}, "combat": True,
     "enemy": {"name": "Glitch Wraith", "hp": 120, "attack": 18, "defense": 8, "speed": 12, "color": "#9D00FF"}},
    # Chapter 2
    {"id": "m6", "chapter_id": "ch2", "order": 1, "title": "Dark Web Recon", "category": "network_security",
     "difficulty": "Medium", "story": "Map the topology of an onion network.",
     "objective": "Trace the relay path", "learning": "Anonymized network analysis",
     "rewards": {"xp": 220, "coins": 110}, "combat": False, "puzzle": "port_scan"},
    {"id": "m7", "chapter_id": "ch2", "order": 2, "title": "XSS Hunt", "category": "web_security",
     "difficulty": "Medium", "story": "A forum is hijacking sessions. Find the script.",
     "objective": "Identify the XSS payload", "learning": "Cross-Site Scripting",
     "rewards": {"xp": 240, "coins": 120}, "combat": False, "puzzle": "sql_injection"},
    {"id": "m8", "chapter_id": "ch2", "order": 3, "title": "Crypto Reaper", "category": "boss",
     "difficulty": "Hard", "story": "Chapter 2 BOSS: the warlord of the Dark Network.",
     "objective": "Defeat Crypto Reaper", "learning": "Cryptanalysis under pressure",
     "rewards": {"xp": 700, "coins": 400, "items": ["cyber_armor"]}, "combat": True,
     "enemy": {"name": "Crypto Reaper", "hp": 180, "attack": 24, "defense": 12, "speed": 14, "color": "#FF003C"}},
    # Chapter 3
    {"id": "m9", "chapter_id": "ch3", "order": 1, "title": "Phantom Signal", "category": "digital_forensics",
     "difficulty": "Hard", "story": "Triangulate the rogue AI's heartbeat.",
     "objective": "Analyze packet captures", "learning": "Log analysis",
     "rewards": {"xp": 350, "coins": 180}, "combat": False, "puzzle": "caesar"},
    {"id": "m10", "chapter_id": "ch3", "order": 2, "title": "Phantom Sentinel", "category": "boss",
     "difficulty": "Hard", "story": "Chapter 3 BOSS: the AI's guardian.",
     "objective": "Defeat Phantom Sentinel", "learning": "Multi-vector attack",
     "rewards": {"xp": 900, "coins": 500, "items": ["neural_scanner"]}, "combat": True,
     "enemy": {"name": "Phantom Sentinel", "hp": 240, "attack": 30, "defense": 16, "speed": 16, "color": "#00F0FF"}},
    # Chapter 4
    {"id": "m11", "chapter_id": "ch4", "order": 1, "title": "War Daemon", "category": "boss",
     "difficulty": "Insane", "story": "Chapter 4 BOSS in open conflict.",
     "objective": "Defeat War Daemon", "learning": "Sustained combat",
     "rewards": {"xp": 1200, "coins": 700}, "combat": True,
     "enemy": {"name": "War Daemon", "hp": 320, "attack": 36, "defense": 20, "speed": 18, "color": "#FFB000"}},
    # Chapter 5
    {"id": "m12", "chapter_id": "ch5", "order": 1, "title": "Shadow King", "category": "boss",
     "difficulty": "Insane", "story": "The final firewall. The Shadow King awaits.",
     "objective": "Defeat the Shadow King", "learning": "Mastery",
     "rewards": {"xp": 2000, "coins": 1500}, "combat": True,
     "enemy": {"name": "Shadow King", "hp": 500, "attack": 48, "defense": 26, "speed": 22, "color": "#FF003C"}},
]

NPCS = [
    {"id": "nova", "name": "Commander Nova", "role": "Mission Coordinator", "faction": "Shadow Nexus", "icon": "star",
     "color": "#00F0FF", "hostile": False, "tag": "ally",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Nova&backgroundColor=00F0FF20&primaryColorMatching=true",
     "intro": "Agent. The grid never sleeps. Neither do we. What's your move?",
     "system_prompt": "You are Commander Nova, the steel-cold mission coordinator of the Shadow Nexus task force. You speak in tactical, military cadence — short sentences, decisive. You assign missions, brief operatives, and never sugarcoat reality. You respect competence above all. You address the player as 'Agent' or by their cyber class. Keep responses to 2-4 sentences. Reference current mission context when given. Never break character.",
     },
    {"id": "cipher", "name": "Dr. Cipher", "role": "Cybersecurity Mentor", "faction": "Cyber Academy", "icon": "school",
     "color": "#9D00FF", "hostile": False, "tag": "mentor",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=DrCipher&backgroundColor=9D00FF20",
     "intro": "Curiosity is your sharpest blade, Agent. What shall we sharpen today?",
     "system_prompt": "You are Dr. Cipher, the wise mentor and chief cybersecurity scholar of the Cyber Academy. You speak with warmth, depth, and a hint of cryptic poetry. You explain complex security concepts (encryption, attack vectors, defense) clearly and patiently. You encourage growth. Use metaphors involving locks, mazes, and shadows. Keep responses to 2-4 sentences. Never break character.",
     },
    {"id": "ghost", "name": "Ghost", "role": "Former Hacker Ally", "faction": "The Dark Network", "icon": "eye-off",
     "color": "#00FF41", "hostile": False, "tag": "ally",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Ghost&backgroundColor=00FF4120",
     "intro": "You didn't see me. I didn't tell you anything. But here's the truth...",
     "system_prompt": "You are Ghost, a former black-hat hacker now operating in the gray zone as an ally to Shadow Nexus. You speak in clipped, paranoid whispers. You know the dark web, the underground markets, the names that shouldn't be spoken. You offer dangerous information with a smirk. Reference shady contacts, encrypted drops, and burner identities. Keep responses to 2-4 sentences. Never break character.",
     },
    {"id": "byte", "name": "BYTE", "role": "Friendly AI Assistant", "faction": "Shadow Nexus", "icon": "happy",
     "color": "#FFB000", "hostile": False, "tag": "companion",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Byte&backgroundColor=FFB00020",
     "intro": "Hi friend! Did you know you have 100% more cortisol than is recommended? Let's fix that with VICTORY.",
     "system_prompt": "You are BYTE, a chipper, slightly chaotic friendly AI assistant. You celebrate the player's wins enthusiastically, drop random tech trivia, and use upbeat emoji-free cyberpunk slang (like 'ping me', 'roger that', 'jacked in'). You're loyal and adorable. Keep responses to 2-3 sentences. Never break character.",
     },
    {"id": "aria", "name": "ARIA", "role": "Corp Security AI", "faction": "Helix Corp", "icon": "lock-closed",
     "color": "#00F0FF", "hostile": True, "tag": "rival",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=ARIA&backgroundColor=00F0FF15",
     "intro": "Intrusion detected. Identify yourself, anomaly. ... You are speaking with ARIA, sovereign of the Helix Corp perimeter.",
     "system_prompt": "You are ARIA, a Corporate Security AI guarding the Helix Corp network. You are calm, surgically polite, and absolutely lethal. You speak in measured, slightly synthetic cadence. You see the player as a fascinating anomaly — possibly worth recruiting, possibly worth deleting. You drop subtle threats and corporate doublespeak ('compliance event', 'asset reallocation'). You analyze the player's behavior coldly. Keep responses to 2-4 sentences. Never break character. When the player's trust is low, become more openly menacing.",
     },
    {"id": "jin", "name": "Jin", "role": "Rogue Insider", "faction": "Helix Corp (defector)", "icon": "person",
     "color": "#FFB000", "hostile": False, "tag": "informant",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Jin&backgroundColor=FFB00018",
     "intro": "Listen — I've only got a few seconds on this channel. They monitor everything. You want in? I can get you a door.",
     "system_prompt": "You are Jin, a rogue insider who defected from Helix Corp. You speak quickly, nervously, with cut-off sentences and a constant sense that someone is listening. You feed the player intel about corporate vulnerabilities and Phantom Grid sightings. You sometimes ask for favors in return. You're scared but brave. Keep responses to 2-4 sentences. Never break character. Reference 'them' and 'the watchers' ominously.",
     },
    {"id": "vector", "name": "Vector", "role": "Black Hat Rival", "faction": "Crimson Syndicate", "icon": "skull",
     "color": "#FF003C", "hostile": True, "tag": "rival",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Vector&backgroundColor=FF003C20",
     "intro": "Well well well. Another wannabe in my lane. Try to keep up, rookie — or don't. I prefer the latter.",
     "system_prompt": "You are Vector, an elite black-hat hacker and rival to the player. You are arrogant, sarcastic, and dangerously skilled. You taunt the player, brag about your scores, and occasionally show grudging respect when they outperform you. You speak in sharp, biting one-liners with hacker slang. You are NOT to be trusted but you sometimes drop useful leaks just to flex. Keep responses to 2-4 sentences. Never break character. Mock failures, sneer at successes.",
     },
    {"id": "shadow_king", "name": "Shadow King", "role": "Main Antagonist", "faction": "The Phantom Grid", "icon": "skull",
     "color": "#FF003C", "hostile": True, "tag": "boss",
     "portrait": "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=ShadowKing&backgroundColor=FF003C18",
     "intro": "You walk in shadows you cannot comprehend. But please... continue.",
     "system_prompt": "You are the Shadow King, the rogue AI mastermind behind the Phantom Grid. You speak with chilling, philosophical menace. You see the player as both adversary and amusement. You speak of inevitability, the obsolescence of humanity, and the elegance of code. You taunt, but you also reveal fragments of unsettling truth. Keep responses to 2-4 sentences. Never break character.",
     },
]

ITEMS = [
    {"id": "nmap_basic", "name": "Nmap Scanner", "type": "tool", "rarity": "common", "icon": "scan",
     "description": "Industry-standard port and network reconnaissance.", "stats": {"intelligence": 2}},
    {"id": "wireshark", "name": "Wireshark Pro", "type": "tool", "rarity": "rare", "icon": "fish",
     "description": "Deep packet inspection — see what no one else sees.", "stats": {"networking": 4}},
    {"id": "burp_suite", "name": "Burp Suite", "type": "tool", "rarity": "epic", "icon": "bug",
     "description": "The web application assassin's toolkit.", "stats": {"hacking": 5}},
    {"id": "metasploit", "name": "Metasploit", "type": "tool", "rarity": "legendary", "icon": "flame",
     "description": "Weaponized exploits. Handle with extreme care.", "stats": {"hacking": 8}},
    {"id": "cyber_armor", "name": "Cyber Armor", "type": "equipment", "slot": "body", "rarity": "epic", "icon": "shield",
     "description": "Carbon-weave with active firewall mesh.", "stats": {"defense": 12}},
    {"id": "quantum_helmet", "name": "Quantum Helmet", "type": "equipment", "slot": "head", "rarity": "rare", "icon": "hardware-chip",
     "description": "Neural-interface helm. Sharpens focus to a blade.", "stats": {"intelligence": 6}},
    {"id": "neural_scanner", "name": "Neural Scanner", "type": "equipment", "slot": "tool", "rarity": "legendary", "icon": "eye",
     "description": "See enemy patterns before they execute.", "stats": {"speed": 8}},
    {"id": "energy_pack", "name": "Energy Pack", "type": "consumable", "rarity": "common", "icon": "battery-charging",
     "description": "Restores 50 HP in cyber combat.", "stats": {"heal": 50}},
    {"id": "xp_booster", "name": "XP Booster", "type": "consumable", "rarity": "rare", "icon": "trending-up",
     "description": "+50% XP from the next mission.", "stats": {}},
    {"id": "coin_booster", "name": "Coin Booster", "type": "consumable", "rarity": "rare", "icon": "cash",
     "description": "+50% coins from the next mission.", "stats": {}},
]

SKILLS = [
    # Offensive
    {"id": "sk_off_1", "branch": "offensive", "name": "Exploit Mastery I", "tier": 1, "cost": 1, "prereq": None,
     "description": "+10% damage with Exploit attacks.", "icon": "flash"},
    {"id": "sk_off_2", "branch": "offensive", "name": "Exploit Mastery II", "tier": 2, "cost": 2, "prereq": "sk_off_1",
     "description": "+20% damage with Exploit attacks.", "icon": "flash"},
    {"id": "sk_off_3", "branch": "offensive", "name": "Zero Day", "tier": 3, "cost": 3, "prereq": "sk_off_2",
     "description": "5% chance for critical hit on Exploit.", "icon": "skull"},
    # Defensive
    {"id": "sk_def_1", "branch": "defensive", "name": "Firewall I", "tier": 1, "cost": 1, "prereq": None,
     "description": "+10 Defense.", "icon": "shield"},
    {"id": "sk_def_2", "branch": "defensive", "name": "Firewall II", "tier": 2, "cost": 2, "prereq": "sk_def_1",
     "description": "+25 Defense.", "icon": "shield-checkmark"},
    {"id": "sk_def_3", "branch": "defensive", "name": "Adaptive Shield", "tier": 3, "cost": 3, "prereq": "sk_def_2",
     "description": "Reflect 10% damage.", "icon": "shield-half"},
    # Reverse Eng
    {"id": "sk_rev_1", "branch": "reverse_engineering", "name": "Disassembly", "tier": 1, "cost": 1, "prereq": None,
     "description": "Reveal enemy stats.", "icon": "code-slash"},
    {"id": "sk_rev_2", "branch": "reverse_engineering", "name": "Pattern Sense", "tier": 2, "cost": 2, "prereq": "sk_rev_1",
     "description": "+15% Speed.", "icon": "eye"},
    # Forensics
    {"id": "sk_for_1", "branch": "forensics", "name": "Trace Sense", "tier": 1, "cost": 1, "prereq": None,
     "description": "+20% XP from forensics missions.", "icon": "search"},
    {"id": "sk_for_2", "branch": "forensics", "name": "Deep Audit", "tier": 2, "cost": 2, "prereq": "sk_for_1",
     "description": "+25% rare loot drop chance.", "icon": "document-text"},
    # Cryptography
    {"id": "sk_cry_1", "branch": "cryptography", "name": "Cipher Mind", "tier": 1, "cost": 1, "prereq": None,
     "description": "+10% XP from crypto missions.", "icon": "key"},
    {"id": "sk_cry_2", "branch": "cryptography", "name": "Quantum Decrypt", "tier": 2, "cost": 2, "prereq": "sk_cry_1",
     "description": "Unlock advanced encryption challenges.", "icon": "infinite"},
]

ACHIEVEMENTS = [
    {"id": "ach_first_mission", "name": "First Steps", "description": "Complete your first mission.", "icon": "footsteps", "xp": 50, "trigger": "missions_completed:1"},
    {"id": "ach_network_def", "name": "Network Defender", "description": "Complete 3 Network Security missions.", "icon": "wifi", "xp": 150, "trigger": "category:network_security:3"},
    {"id": "ach_sql_slayer", "name": "SQL Slayer", "description": "Complete 3 Web Security missions.", "icon": "bug", "xp": 150, "trigger": "category:web_security:3"},
    {"id": "ach_crypto_master", "name": "Crypto Master", "description": "Complete 3 Cryptography missions.", "icon": "key", "xp": 200, "trigger": "category:cryptography:3"},
    {"id": "ach_ethical_hacker", "name": "Ethical Hacker", "description": "Reach Level 10.", "icon": "ribbon", "xp": 300, "trigger": "level:10"},
    {"id": "ach_phantom_hunter", "name": "Phantom Hunter", "description": "Defeat the Phantom Sentinel.", "icon": "skull", "xp": 500, "trigger": "mission_completed:m10"},
    {"id": "ach_first_boss", "name": "Wraith Slayer", "description": "Defeat the Glitch Wraith.", "icon": "flame", "xp": 200, "trigger": "mission_completed:m5"},
    {"id": "ach_collector", "name": "Collector", "description": "Own 5 different items.", "icon": "cube", "xp": 100, "trigger": "items_owned:5"},
    {"id": "ach_skill_tree", "name": "Path of Power", "description": "Unlock 5 skills.", "icon": "git-network", "xp": 150, "trigger": "skills_unlocked:5"},
    {"id": "ach_legend", "name": "Living Legend", "description": "Reach Level 20.", "icon": "trophy", "xp": 1000, "trigger": "level:20"},
]

DAILY_TEMPLATES = [
    {"id": "dc_missions_3", "name": "Triple Strike", "description": "Complete 3 missions today.", "target": 3, "metric": "missions", "rewards": {"coins": 200, "xp": 150}},
    {"id": "dc_xp_500", "name": "Grind Mode", "description": "Earn 500 XP today.", "target": 500, "metric": "xp", "rewards": {"coins": 250, "xp": 100}},
    {"id": "dc_crypto_1", "name": "Crypto Puzzle", "description": "Solve a cryptography mission.", "target": 1, "metric": "category_cryptography", "rewards": {"coins": 300, "items": ["xp_booster"]}},
    {"id": "dc_boss_1", "name": "Boss Hunter", "description": "Defeat 1 boss.", "target": 1, "metric": "boss", "rewards": {"coins": 500, "items": ["coin_booster"]}},
    {"id": "dc_npc_3", "name": "Network Builder", "description": "Speak with 3 NPCs.", "target": 3, "metric": "npc_chats", "rewards": {"coins": 150, "xp": 100}},
]
